name: Mobile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: 'super-app-mobile/package.json'

    - name: Install dependencies
      run: npm ci
      working-directory: ./super-app-mobile

    - name: Run build check
      run: npm run build --if-present
      working-directory: ./super-app-mobile
